---

- name: Install necessary packages and fonts
  apt:
    name={{ item }}
    update_cache=yes
    cache_valid_time=86400
    install-recommends=no
    state=present
  with_items:
    - default-jre-headless
    - fonts-liberation
    - unzip
